import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { judgeSurfaceSinceTag, pickLastReleaseTag, loadLastReleaseSnapshot } from "../scripts/check-surface.js";

// The per-PR snapshot is regenerated by every PR, so `check:surface` against it reads +0 at release time
// whatever changed since the last release. These tests pin the release-time diff against the last TAG's
// snapshot: a removed or narrowed leaf must fail unless the version being released is a MAJOR bump.

const tagSnap = { schemas: { "s.json": { ".a": { type: "string" }, ".b": { type: "number" } } } };
const removedB = { schemas: { "s.json": { ".a": { type: "string" } } } };
const changedB = { schemas: { "s.json": { ".a": { type: "string" }, ".b": { type: "string" } } } };
const addedC = { schemas: { "s.json": { ".a": { type: "string" }, ".b": { type: "number" }, ".c": { type: "boolean" } } } };
const widenedB = {
  schemas: {
    "s.json": {
      ".a": { type: "string" },
      ".b<anyOf:0>": { type: "number" },
      ".b<anyOf:1>": { type: "object" },
    },
  },
};

describe("judgeSurfaceSinceTag", () => {
  it("FAILS a removed leaf on a MINOR bump, and lists it", () => {
    const v = judgeSurfaceSinceTag({ tag: "v4.2.1", tagSnapshot: tagSnap, current: removedB, version: "4.3.0" });
    expect(v.status).toBe("FAIL");
    expect(v.detail).toContain("schemas.s.json..b.type");
    expect(v.detail).toContain("MAJOR");
  });

  it("FAILS a changed (narrowed) leaf on a PATCH bump", () => {
    const v = judgeSurfaceSinceTag({ tag: "v4.2.1", tagSnapshot: tagSnap, current: changedB, version: "4.2.2" });
    expect(v.status).toBe("FAIL");
    expect(v.detail).toContain("schemas.s.json..b.type");
  });

  it("PASSES the same removal on a MAJOR bump, still listing the break", () => {
    const v = judgeSurfaceSinceTag({ tag: "v4.2.1", tagSnapshot: tagSnap, current: removedB, version: "5.0.0" });
    expect(v.status).toBe("PASS");
    expect(v.detail).toContain("schemas.s.json..b.type");
  });

  it("PASSES additions only on a MINOR bump", () => {
    const v = judgeSurfaceSinceTag({ tag: "v4.2.1", tagSnapshot: tagSnap, current: addedC, version: "4.3.0" });
    expect(v.status).toBe("PASS");
    expect(v.detail).toContain("+1 −0 ~0");
  });

  it("PASSES a widening (scalar kept as a union arm) on a PATCH bump", () => {
    const v = judgeSurfaceSinceTag({ tag: "v4.2.1", tagSnapshot: tagSnap, current: widenedB, version: "4.2.2" });
    expect(v.status).toBe("PASS");
    expect(v.detail).toContain("1 widened");
  });

  it("before the bump (version == tag) a break is informational: WARN, never FAIL", () => {
    const v = judgeSurfaceSinceTag({ tag: "v4.2.1", tagSnapshot: tagSnap, current: removedB, version: "4.2.1" });
    expect(v.status).toBe("WARN");
    expect(v.detail).toContain("not bumped yet");
    expect(v.detail).toContain("schemas.s.json..b.type");
  });

  it("SKIPS when the tag carries no snapshot", () => {
    const v = judgeSurfaceSinceTag({ tag: "v0.9.0", tagSnapshot: undefined, current: addedC, version: "4.3.0" });
    expect(v.status).toBe("SKIP");
    expect(v.detail).toContain("v0.9.0");
  });

  it("FAILS an unparseable release version rather than guessing", () => {
    const v = judgeSurfaceSinceTag({ tag: "v4.2.1", tagSnapshot: tagSnap, current: addedC, version: "4.3" });
    expect(v.status).toBe("FAIL");
  });
});

describe("pickLastReleaseTag", () => {
  it("picks the highest X.Y.Z numerically, not lexically", () => {
    expect(pickLastReleaseTag(["v4.9.0", "v4.10.0", "v4.2.1"])).toBe("v4.10.0");
  });

  it("ignores the moving vX / vX.Y alias tags and pre-release tags", () => {
    expect(pickLastReleaseTag(["v4.2.1", "v4", "v4.3", "v5", "v4.3.0-rc.1", "latest"])).toBe("v4.2.1");
  });

  it("returns undefined with no release tag", () => {
    expect(pickLastReleaseTag(["v4", "v4.2"])).toBeUndefined();
    expect(pickLastReleaseTag([])).toBeUndefined();
  });
});

// The git wrapper, against a real temp repo: an alias at the same commit is excluded, a higher tag that is
// NOT an ancestor of HEAD is never picked, and a tag commit lacking the snapshot file skips.
describe("loadLastReleaseSnapshot (temp git repo)", () => {
  let dir: string;
  const git = (...args: string[]) => {
    const r = spawnSync(
      "git",
      ["-c", "user.name=t", "-c", "user.email=t@example.com", "-c", "commit.gpgsign=false", "-c", "tag.gpgsign=false", ...args],
      {
        cwd: dir,
        encoding: "utf8",
      },
    );
    if (r.status !== 0) throw new Error(`git ${args.join(" ")}: ${r.stderr}`);
    return r.stdout;
  };
  const snapPath = () => join(dir, "test/fixtures/surface-baseline.json");

  beforeAll(() => {
    dir = mkdtempSync(join(tmpdir(), "surface-since-tag-"));
    git("init", "-q", "-b", "main");
    writeFileSync(join(dir, "README"), "x\n");
    git("add", "README");
    git("commit", "-q", "-m", "no snapshot yet");
    git("tag", "v0.9.0");
  });
  afterAll(() => rmSync(dir, { recursive: true, force: true }));

  it("SKIPs (snapshot undefined) when the last tag predates the snapshot file", () => {
    const r = loadLastReleaseSnapshot(dir);
    expect(r).toEqual({ tag: "v0.9.0", tagSnapshot: undefined });
  });

  it("loads the last ancestor X.Y.Z tag's snapshot, ignoring aliases and non-ancestor tags", () => {
    mkdirSync(join(dir, "test/fixtures"), { recursive: true });
    writeFileSync(snapPath(), JSON.stringify(tagSnap));
    git("add", "test/fixtures/surface-baseline.json");
    git("commit", "-q", "-m", "snapshot");
    git("tag", "v1.0.0");
    git("tag", "v1");
    git("tag", "v1.9");
    // A higher tag on a side branch that HEAD does not contain.
    git("checkout", "-q", "-b", "side");
    writeFileSync(snapPath(), JSON.stringify(removedB));
    git("commit", "-q", "-am", "side");
    git("tag", "v9.0.0");
    git("checkout", "-q", "main");
    writeFileSync(snapPath(), JSON.stringify(addedC));
    git("commit", "-q", "-am", "head moves on");

    const r = loadLastReleaseSnapshot(dir);
    expect(r).toEqual({ tag: "v1.0.0", tagSnapshot: tagSnap });
  });

  it("returns no tag at all when none is reachable", () => {
    const empty = mkdtempSync(join(tmpdir(), "surface-since-tag-empty-"));
    try {
      spawnSync("git", ["init", "-q"], { cwd: empty });
      spawnSync(
        "git",
        ["-c", "user.name=t", "-c", "user.email=t@example.com", "-c", "commit.gpgsign=false", "commit", "-q", "--allow-empty", "-m", "x"],
        {
          cwd: empty,
        },
      );
      expect(loadLastReleaseSnapshot(empty)).toEqual({ tag: undefined, tagSnapshot: undefined });
    } finally {
      rmSync(empty, { recursive: true, force: true });
    }
  });
});
