import { describe, it, expect } from "vitest";
import { outputsDeleteBasis, isOutputsDelete } from "../src/run/execute.js";

/**
 * The outputs-delete basis classifier, pinned over a wide table of command shapes.
 *
 * Each row: [id, command, detector flags it?, basis under the original statement-level rule (a delete word and
 * an outputs path anywhere in one statement), basis under the first operand-level rule, basis expected now].
 * The two historical columns are kept as a record of how each shape moved; only the last is asserted. `null`
 * means the detector does not flag the shape at all (so there is no basis); `"any"` marks a shape that is not
 * a realistic command, where no basis is claimed.
 *
 * Rows A* and B* are real deletes, false positives and non-deletes across shell, `find`/`xargs`, Python and
 * other interpreters; rows X* are `xargs … echo rm` dry runs that must never read as a delete. The motivating
 * false positive (a Python variable named `rm` next to an outputs path) lives in outputs-delete-basis.test.ts.
 * Expectations for real deletes that still read `inferred` are the documented false-negative classes.
 */
type Basis = "named" | "inferred";
type Row = [id: string, cmd: string, flags: boolean, statementRule: Basis | "—", operandRuleV1: Basis | "—", want: Basis | "any" | null];

const ROWS: Row[] = [
  ["A1", 'rm -rf -- "/sessions/s/mnt/outputs/x"', true, "named", "named", "named"],
  ["A2", "rm -r -f /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A3", "\\rm -f /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A4", "command rm -f /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A5", "builtin rm -f /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A6", "/usr/bin/rm -f /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A7", "busybox rm -f /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A8", "git rm -f /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A9", "git rm --cached /sessions/s/mnt/outputs/x", true, "named", "inferred", "inferred"],
  ["A10", "rm -f /sessions/s/mnt/outputs/{a,b}", true, "named", "named", "named"],
  ["A11", "rm /sessions/s/mnt/outputs/*.tmp", true, "named", "named", "named"],
  ["A12", "[ -f /sessions/s/mnt/outputs/x ] && rm /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A13", "test -e /sessions/s/mnt/outputs/x && rm -f /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A14", '[ -f /sessions/s/mnt/outputs/x ] && rm -f "/sessions/s/mnt/outputs/x" || true', true, "named", "named", "named"],
  ["A15", 'cd /sessions/s/mnt && rm "$(pwd)/outputs/x"', true, "named", "named", "named"],
  ["A16", "cd /sessions/s/mnt && rm outputs/x", true, "named", "named", "named"],
  ["A17", "rm -f `ls /sessions/s/mnt/outputs/*.tmp`", true, "named", "inferred", "named"],
  ["A18", "echo `rm -f /sessions/s/mnt/outputs/x`", true, "named", "named", "named"],
  ["A19", "! rm -f /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A20", "time rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A21", "if rm -f /sessions/s/mnt/outputs/x; then echo ok; fi", true, "named", "inferred", "named"],
  ["A22", "while rm -f /sessions/s/mnt/outputs/x; do :; done", true, "named", "inferred", "named"],
  ["A23", "true & rm -f /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A24", 'eval "rm -f /sessions/s/mnt/outputs/x"', true, "named", "inferred", "named"],
  ["A25", "bash -lc 'rm -f /sessions/s/mnt/outputs/x'", true, "named", "inferred", "named"],
  ["A26", 'sh -c "rm -f /sessions/s/mnt/outputs/x"', true, "named", "named", "named"],
  ["A27", 'bash -c "cd /tmp && rm -f /sessions/s/mnt/outputs/x"', true, "named", "named", "named"],
  ["A28", "nohup rm -rf /sessions/s/mnt/outputs/x &", true, "named", "named", "named"],
  ["A29", "timeout 10s rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A30", "timeout --signal=KILL 5 rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A31", "ionice -c 3 rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A32", "nice rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A33", "sudo -u user rm -rf /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A34", "env FOO=1 rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A35", "FOO=1 BAR=2 rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A36", 'rm -rf "/sessions/s/mnt/outputs"/', true, "named", "named", "named"],
  ["A37", "rm -rf /sessions/s/mnt/outputs/x /sessions/s/mnt/outputs/y", true, "named", "named", "named"],
  ["A38", "rm -rf /tmp/scratch /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A39", 'rm -f "/sessions/s/mnt/outputs/x" # done', true, "named", "named", "named"],
  ["A40", 'rm -f "/sessions/s/mnt/outputs/x"; echo cleaned', true, "named", "named", "named"],
  ["A41", "{ rm -f /sessions/s/mnt/outputs/x; }", true, "named", "named", "named"],
  ["A42", "{ rm -f /sessions/s/mnt/outputs/x; } 2>/dev/null", true, "named", "named", "named"],
  ["A43", "trash /sessions/s/mnt/outputs/x", false, "—", "—", null],
  ["A44", "rmdir --ignore-fail-on-non-empty /sessions/s/mnt/outputs/empty", true, "named", "named", "named"],
  ["A45", 'unlink "/sessions/s/mnt/outputs/x"', true, "named", "named", "named"],
  ["A46", "shred -n 1 -u /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A47", "shred --remove=wipe /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A48", "shred -z /sessions/s/mnt/outputs/x", false, "—", "—", null],
  ["A49", "rm -rf /sessions/s/mnt/outputs/x |& tee log", true, "named", "named", "named"],
  ["A50", "cat list | rm -f /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A51", "ls | while read f; do rm -f /sessions/s/mnt/outputs/x; done", true, "named", "named", "named"],
  ["A52", 'for f in a b; do rm -f "/sessions/s/mnt/outputs/$f"; done', true, "named", "named", "named"],
  ["A53", 'rm -rf "${OUT:-/sessions/s/mnt/outputs}/x"', true, "named", "named", "named"],
  ["A54", 'OUT=/sessions/s/mnt/outputs\nrm -rf "${OUT}/x"', true, "named", "named", "named"],
  ["A55", "rm  -rf   /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A56", "\trm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A57", "rm -rf /sessions/s/mnt/outputs/x\n", true, "named", "named", "named"],
  ["A58", "rm -rf '/sessions/s/mnt/outputs/x' && echo \"rm = done\"", true, "named", "named", "named"],
  ["A59", "rm -f /sessions/s/mnt/outputs/x; rm=1", true, "named", "named", "named"],
  ["A60", "rm=1; rm -f /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A61", "(rm -rf /sessions/s/mnt/outputs/x)", true, "named", "named", "named"],
  ["A62", "case $1 in rm) rm -rf /sessions/s/mnt/outputs/x ;; esac", true, "named", "inferred", "named"],
  ["A63", "case $1 in rm) echo x ;; esac; rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A64", "rm -rf /sessions/s/mnt/outputs/x || exit 1", true, "named", "named", "named"],
  ["A65", "rm -rf /sessions/s/mnt/outputs/x 2>&1 | tail -1", true, "named", "named", "named"],
  ["A66", "rm -rf /sessions/s/mnt/outputs/x >/dev/null", true, "named", "named", "named"],
  ["A67", "2>/dev/null rm -rf /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A68", "exec rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A69", "xargs rm -f < list", false, "—", "—", null],
  ["A70", "printf '%s\\0' /sessions/s/mnt/outputs/*.tmp | xargs -0 rm -f", true, "named", "named", "named"],
  ["A71", "find /sessions/s/mnt/outputs -name '*.tmp' | xargs -I{} rm -f {}", true, "named", "inferred", "named"],
  ["A72", "find /sessions/s/mnt/outputs -name '*.tmp' | xargs -I {} rm -f {}", true, "named", "inferred", "named"],
  ["A73", "ls /sessions/s/mnt/outputs/*.tmp | xargs -n 1 rm -f", true, "named", "inferred", "named"],
  ["A74", "ls /sessions/s/mnt/outputs/*.tmp | xargs -d '\\n' rm -f", true, "named", "inferred", "named"],
  ["A75", "ls /sessions/s/mnt/outputs/*.tmp | xargs -0 -I{} rm -f {}", true, "named", "inferred", "named"],
  ["A76", "ls /sessions/s/mnt/outputs/*.tmp | xargs -r rm -f", true, "named", "named", "named"],
  ["A77", "ls /sessions/s/mnt/outputs/*.tmp | xargs --no-run-if-empty rm -f", true, "named", "named", "named"],
  ["A78", "ls /sessions/s/mnt/outputs/*.tmp | xargs -P 4 rm -f", true, "named", "inferred", "named"],
  ["A79", "ls /sessions/s/mnt/outputs/*.tmp | parallel rm -f", true, "named", "inferred", "named"],
  ["A80", "ls /sessions/s/mnt/outputs/*.tmp | xargs sudo rm -f", true, "named", "inferred", "named"],
  ["A81", "ls /sessions/s/mnt/outputs/*.tmp | xargs -I{} sh -c 'rm -f {}'", true, "named", "inferred", "named"],
  ["A82", "find /sessions/s/mnt/outputs -name '*.tmp' -exec rm {} +", true, "named", "named", "named"],
  ["A83", "find /sessions/s/mnt/outputs -type f -name '*.tmp' -exec rm -f {} \\;", true, "named", "named", "named"],
  ["A84", "find /sessions/s/mnt/outputs -name '*.tmp' -execdir rm {} \\;", true, "named", "named", "named"],
  ["A85", "find /sessions/s/mnt/outputs -name '*.tmp' -exec /bin/rm {} +", true, "named", "named", "named"],
  ["A86", "find /sessions/s/mnt/outputs -empty -type d -delete", true, "named", "named", "named"],
  ["A87", "find /sessions/s/mnt/outputs -name '*.tmp' -ok rm {} \\;", true, "named", "inferred", "named"],
  ["A88", "find /sessions/s/mnt/outputs -name '*.tmp' -exec unlink {} \\;", true, "named", "inferred", "named"],
  ["A89", "find /sessions/s/mnt/outputs -name '*.tmp' -exec shred -u {} \\;", true, "named", "inferred", "named"],
  ["A90", "find . -path '*/outputs/*' -name '*.tmp' -delete", true, "named", "inferred", "named"],
  ["A91", "find /sessions/s/mnt -name '*.tmp' -delete", false, "—", "—", null],
  ["A92", "fd -e tmp . /sessions/s/mnt/outputs -x rm", true, "named", "inferred", "named"],
  ["A93", "find /sessions/s/mnt/outputs -name '*.tmp' -print0 | xargs -0 rm", true, "named", "named", "named"],
  ["A94", "python3 -c \"import os;os.remove('/sessions/s/mnt/outputs/x')\"", true, "named", "named", "named"],
  ["A95", "python3 -c \"import os; os.remove(r'/sessions/s/mnt/outputs/x')\"", true, "named", "named", "named"],
  [
    "A96",
    "python3 -c \"from pathlib import Path; Path('/sessions/s/mnt/outputs/x').unlink(missing_ok=True)\"",
    true,
    "named",
    "named",
    "named",
  ],
  ["A97", "python3 -c \"from pathlib import Path; Path('/sessions/s/mnt/outputs/x').unlink()\"", true, "named", "named", "named"],
  [
    "A98",
    "python3 -c \"from pathlib import Path; Path('/sessions/s/mnt/outputs').joinpath('x').unlink()\"",
    true,
    "named",
    "named",
    "named",
  ],
  ["A99", "python3 -c \"from pathlib import Path; (Path('/sessions/s/mnt/outputs') / 'x').unlink()\"", true, "named", "named", "named"],
  ["A100", "python3 -c \"import os; os.system('rm -rf /sessions/s/mnt/outputs/x')\"", true, "named", "inferred", "named"],
  [
    "A101",
    "python3 -c \"import subprocess; subprocess.run(['rm', '-rf', '/sessions/s/mnt/outputs/x'])\"",
    true,
    "named",
    "inferred",
    "named",
  ],
  [
    "A102",
    "python3 -c \"import subprocess; subprocess.call('rm -rf /sessions/s/mnt/outputs/x', shell=True)\"",
    true,
    "named",
    "inferred",
    "named",
  ],
  [
    "A103",
    "python3 -c \"import subprocess; subprocess.check_call('rm -rf /sessions/s/mnt/outputs/x', shell=True)\"",
    true,
    "named",
    "inferred",
    "named",
  ],
  ["A104", "python3 -c \"import shutil; shutil.move('/sessions/s/mnt/outputs/x', '/tmp/')\"", false, "—", "—", null],
  ["A105", "python3 -c \"import os; os.unlink('/sessions/s/mnt/outputs/x')\"", true, "named", "named", "named"],
  ["A106", "python3 -c \"from os import remove; remove('/sessions/s/mnt/outputs/x')\"", false, "—", "—", null],
  ["A107", "python3 -c \"from os import unlink; unlink('/sessions/s/mnt/outputs/x')\"", true, "named", "inferred", "named"],
  ["A108", "python3 -c \"import os; os.removedirs('/sessions/s/mnt/outputs/a/b')\"", false, "—", "—", null],
  [
    "A109",
    "python3 -c \"import os, glob; for f in glob.glob('/sessions/s/mnt/outputs/*.tmp'): os.remove(f)\"",
    true,
    "named",
    "inferred",
    "any",
  ],
  [
    "A110",
    "python3 -c \"import os, glob\nfor f in glob.glob('/sessions/s/mnt/outputs/*.tmp'):\n    os.remove(f)\"",
    true,
    "inferred",
    "inferred",
    "inferred",
  ],
  [
    "A111",
    "python3 -c \"import os, glob; list(map(os.remove, glob.glob('/sessions/s/mnt/outputs/*.tmp')))\"",
    true,
    "named",
    "inferred",
    "named",
  ],
  [
    "A112",
    "python3 -c \"import os, glob; [os.remove(p) for p in glob.glob('/sessions/s/mnt/outputs/*.tmp')]\"",
    true,
    "named",
    "named",
    "named",
  ],
  [
    "A113",
    "python3 -c \"import os, glob; (os.remove(p) for p in glob.glob('/sessions/s/mnt/outputs/*.tmp'))\"",
    true,
    "named",
    "named",
    "named",
  ],
  [
    "A114",
    "python3 -c \"import os, glob; [os.remove(p) for p in glob.glob('/sessions/s/mnt/outputs/*.tmp') if p.endswith('.tmp')]\"",
    true,
    "named",
    "named",
    "named",
  ],
  [
    "A115",
    "python3 -c \"import shutil; shutil.rmtree('/sessions/s/mnt/outputs/pkg', ignore_errors=True)\"",
    true,
    "named",
    "named",
    "named",
  ],
  [
    "A116",
    "python3 -c \"import shutil, os; shutil.rmtree(os.path.join('/sessions/s/mnt/outputs', 'pkg'))\"",
    true,
    "named",
    "named",
    "named",
  ],
  [
    "A117",
    "python3 -c \"import os; os.remove('/sessions/s/mnt/outputs/x') if os.path.exists('/sessions/s/mnt/outputs/x') else None\"",
    true,
    "named",
    "named",
    "named",
  ],
  [
    "A118",
    "python3 -c \"import os; os.path.exists('/sessions/s/mnt/outputs/x') and os.remove('/sessions/s/mnt/outputs/x')\"",
    true,
    "named",
    "named",
    "named",
  ],
  ["A119", "python3 -c \"import os; os.remove(f'/sessions/s/mnt/outputs/{name}')\"", true, "named", "named", "named"],
  ["A120", "python3 -c \"import os; os.remove('/sessions/s/mnt/outputs' + '/x')\"", true, "named", "named", "named"],
  [
    "A121",
    'python3 - <<\'EOF\'\nfrom pathlib import Path\nfor p in Path("/sessions/s/mnt/outputs").glob("*.tmp"):\n    p.unlink()\nEOF',
    true,
    "inferred",
    "inferred",
    "inferred",
  ],
  [
    "A122",
    'python3 - <<\'EOF\'\nfrom pathlib import Path\n[p.unlink() for p in Path("/sessions/s/mnt/outputs").glob("*.tmp")]\nEOF',
    true,
    "named",
    "named",
    "named",
  ],
  ["A123", "python3 -c \"import os; os.remove(os.environ['OUT'] + '/x')\"", false, "—", "—", null],
  ["A124", "python3 -c \"import os; p = '/sessions/s/mnt/outputs/x'; os.remove(p)\"", true, "inferred", "inferred", "inferred"],
  ["A125", "python3 -c \"import os; os.remove('/sessions/s/mnt/outputs/x'); rm = 1\"", true, "named", "named", "named"],
  ["A126", "python3 -c \"import os; os.rename('/sessions/s/mnt/outputs/x', '/tmp/x')\"", false, "—", "—", null],
  ["A127", "python3 -c \"import os; os.replace('/sessions/s/mnt/outputs/x', '/tmp/x')\"", false, "—", "—", null],
  ["A128", "node -e \"fs.unlinkSync('/sessions/s/mnt/outputs/x')\"", false, "—", "—", null],
  ["A129", "node -e \"require('fs').rmSync('/sessions/s/mnt/outputs', {recursive: true})\"", false, "—", "—", null],
  ["A130", "node -e \"require('fs/promises').rm('/sessions/s/mnt/outputs/x')\"", true, "named", "inferred", "inferred"],
  ["A131", "node -e \"require('fs').rmdirSync('/sessions/s/mnt/outputs/d')\"", false, "—", "—", null],
  ["A132", "perl -e 'unlink \"/sessions/s/mnt/outputs/x\"'", true, "named", "inferred", "named"],
  ["A133", "perl -e 'unlink(\"/sessions/s/mnt/outputs/x\")'", true, "named", "inferred", "named"],
  ["A134", "perl -e 'unlink glob \"/sessions/s/mnt/outputs/*.tmp\"'", true, "named", "inferred", "named"],
  ["A135", "ruby -e 'File.unlink(\"/sessions/s/mnt/outputs/x\")'", true, "named", "named", "named"],
  ["A136", "ruby -e 'File.delete(\"/sessions/s/mnt/outputs/x\")'", false, "—", "—", null],
  ["A137", "ruby -e 'FileUtils.rm_rf(\"/sessions/s/mnt/outputs/x\")'", false, "—", "—", null],
  ["A138", "php -r 'unlink(\"/sessions/s/mnt/outputs/x\");'", true, "named", "inferred", "named"],
  ["A139", ": > /sessions/s/mnt/outputs/x", false, "—", "—", null],
  ["A140", "truncate -s 0 /sessions/s/mnt/outputs/x", false, "—", "—", null],
  ["A141", "> /sessions/s/mnt/outputs/x", false, "—", "—", null],
  ["A142", "echo '' > /sessions/s/mnt/outputs/x", false, "—", "—", null],
  ["A143", "rsync -a --delete src/ /sessions/s/mnt/outputs/", false, "—", "—", null],
  ["A144", "git clean -fdx /sessions/s/mnt/outputs", false, "—", "—", null],
  ["A145", "mv /sessions/s/mnt/outputs/a /sessions/s/mnt/outputs/b", false, "—", "—", null],
  ["A146", "cp /sessions/s/mnt/outputs/x /tmp/", false, "—", "—", null],
  ["A147", "docker run --rm -v /sessions/s/mnt/outputs:/o img", true, "named", "inferred", "inferred"],
  ["A148", "grep -w rm /sessions/s/mnt/outputs/log.txt", true, "named", "inferred", "inferred"],
  ["A149", 'echo "rm -rf /sessions/s/mnt/outputs/x"', true, "named", "inferred", "inferred"],
  ["A150", 'echo "please run: rm -rf /sessions/s/mnt/outputs/x" > note.txt', true, "named", "inferred", "inferred"],
  ["A151", 'git commit -m "rm stale /sessions/s/mnt/outputs/x"', true, "named", "inferred", "inferred"],
  ["A152", 'echo "done; rm -rf /sessions/s/mnt/outputs/x"', true, "named", "named", "named"],
  ["A153", "cat <<EOF > clean.sh\nrm -rf /sessions/s/mnt/outputs/x\nEOF", true, "named", "named", "named"],
  ["A154", "python3 -c \"print('rm -rf /sessions/s/mnt/outputs/x')\"", true, "named", "inferred", "inferred"],
  ["A155", "npm rm some-pkg --prefix /sessions/s/mnt/outputs/pkg", true, "named", "inferred", "inferred"],
  ["A156", "git rm --cached /sessions/s/mnt/outputs/x", true, "named", "inferred", "inferred"],
  ["A157", "ls -la /sessions/s/mnt/outputs/rm", true, "named", "inferred", "inferred"],
  ["A158", "ls -la /sessions/s/mnt/outputs/rm/", true, "named", "inferred", "inferred"],
  ["A159", "cat /sessions/s/mnt/outputs/rm.txt", true, "named", "inferred", "inferred"],
  [
    "A160",
    "python3 -c \"import re; rm = re.compile('x'); print(rm.match(open('/sessions/s/mnt/outputs/r').read()))\"",
    true,
    "named",
    "inferred",
    "inferred",
  ],
  ["A161", "python3 -c \"rm, ok = 1, open('/sessions/s/mnt/outputs/r').read()\"", true, "named", "inferred", "inferred"],
  ["A162", "python3 -c \"d = {'rm': open('/sessions/s/mnt/outputs/r').read()}\"", true, "named", "inferred", "inferred"],
  ["A163", "python3 -c \"x = (rm) if open('/sessions/s/mnt/outputs/r') else 0\"", true, "named", "inferred", "inferred"],
  ["A164", "python3 -c \"f(rm, open('/sessions/s/mnt/outputs/r'))\"", true, "named", "inferred", "inferred"],
  ["A165", 'python3 -c "import os; print(os.remove)"', false, "—", "—", null],
  [
    "A166",
    "python3 -c \"import os; help(os.remove); print(open('/sessions/s/mnt/outputs/r').read())\"",
    true,
    "inferred",
    "inferred",
    "inferred",
  ],
  ["A167", "sed -n '/^rm /p' /sessions/s/mnt/outputs/script.sh", true, "named", "inferred", "inferred"],
  ["A168", "awk '/rm/ {print}' /sessions/s/mnt/outputs/log", true, "named", "inferred", "inferred"],
  ["A169", "echo rm > /sessions/s/mnt/outputs/cmd.txt", true, "named", "inferred", "inferred"],
  ["A170", "rm -rf /tmp/build && cp -r /tmp/build/out /sessions/s/mnt/outputs/", false, "—", "—", null],
  ["A171", 'rm -rf "$UNSET" && cp x /sessions/s/mnt/outputs/', true, "inferred", "inferred", "inferred"],
  ["A172", "rm -f x; rm=1", false, "—", "—", null],
  ["A173", "(rm -rf /sessions/s/mnt/outputs/x)", true, "named", "named", "named"],
  ["A174", "case x in rm) rm -rf /sessions/s/mnt/outputs/x;; esac", true, "named", "inferred", "named"],
  ["A175", "rm -rf /sessions/s/mnt/outputs/x; rm=done", true, "named", "named", "named"],
  ["A176", "rm -rf /sessions/s/mnt/outputs/x ; rm: nothing", true, "named", "named", "named"],
  ["A177", "rm.sh /sessions/s/mnt/outputs/x", true, "named", "inferred", "inferred"],
  ["A178", "./rm /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A179", "rm(){ echo no; }; rm /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A180", "rm -rf /sessions/s/mnt/outputs/x #rm=1", true, "named", "named", "named"],
  ["A181", "rm -rf /sessions/s/mnt/outputs/x)", true, "named", "named", "named"],
  ["A182", "rm -rf /sessions/s/mnt/outputs/x }", true, "named", "named", "named"],
  ["A183", "rm -rf /sessions/s/mnt/outputs/x,/sessions/s/mnt/outputs/y", true, "named", "named", "named"],
  ["A184", "rm -rf /sessions/s/mnt/outputs/x=1", true, "named", "named", "named"],
  ["A185", "rm ,/sessions/s/mnt/outputs/x", true, "named", "inferred", "any"],
  ["A186", "rm =/sessions/s/mnt/outputs/x", true, "named", "inferred", "any"],
  ["A187", "rm (/sessions/s/mnt/outputs/x)", true, "named", "inferred", "any"],
  ["A188", "rm .//sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A189", "rm ./sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A190", "rm .hidden /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A191", "rm -rf .cache /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["A192", "rm .tmp/* /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A193", "rm ../outputs/x", true, "named", "inferred", "named"],
  ["A194", "rm ../mnt/outputs/x", true, "named", "inferred", "named"],
  ["A195", "rm [a-z]/sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["A196", "rm :/sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["B1", "rm ./mnt/outputs/report.md", true, "named", "inferred", "named"],
  ["B2", "rm ./outputs/report.md", true, "named", "inferred", "named"],
  ["B3", "rm -f ./outputs/report.md", true, "named", "named", "named"],
  ["B4", "rm ../outputs/report.md", true, "named", "inferred", "named"],
  ["B5", "rm -rf ./outputs/scratch", true, "named", "named", "named"],
  ["B6", "rm .DS_Store mnt/outputs/x", true, "named", "inferred", "named"],
  ["B7", "rm /sessions/s/mnt/outputs/.DS_Store", true, "named", "named", "named"],
  ["B8", "rm -f /sessions/s/mnt/outputs/.hidden", true, "named", "named", "named"],
  ["B9", "find ./mnt/outputs -name '*.tmp' -delete", true, "named", "inferred", "named"],
  ["B10", "find ./outputs -name '*.tmp' -delete", true, "named", "inferred", "named"],
  ["B11", "find . -path './mnt/outputs/*' -name '*.tmp' -delete", true, "named", "inferred", "named"],
  ["B12", "find . -name '*.tmp' -delete", false, "—", "—", null],
  ["B13", "cd mnt/outputs && find . -name '*.tmp' -delete", true, "inferred", "inferred", "inferred"],
  ["B14", "find /sessions/s/mnt/outputs -name '*.tmp' -delete", true, "named", "named", "named"],
  ["B15", "find ./mnt/outputs -name '*.tmp' -exec rm {} +", true, "named", "inferred", "named"],
  ["B16", "find mnt/outputs -name '*.tmp' -exec rm -f {} \\;", true, "named", "named", "named"],
  ["B17", "find \"/sessions/s/mnt/outputs\" -name '*.tmp' -delete", true, "named", "named", "named"],
  ["B18", "find '/sessions/s/mnt/outputs' -name '*.tmp' -delete", true, "named", "named", "named"],
  ["B19", 'rm "/sessions/s/mnt/outputs/x"', true, "named", "named", "named"],
  ["B20", "rm '/sessions/s/mnt/outputs/x'", true, "named", "named", "named"],
  ["B21", "rm /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["B22", "rm mnt/outputs/x", true, "named", "named", "named"],
  ["B23", "rm -- mnt/outputs/x", true, "named", "named", "named"],
  ["B24", "rm [0-9]*.log /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["B25", "rm *.log /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["B26", "rm {a,b} /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["B27", "rm ~/x /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["B28", "ls /sessions/s/mnt/outputs/*.tmp | xargs rm", true, "named", "named", "named"],
  ["B29", "ls /sessions/s/mnt/outputs/*.tmp | xargs -0 rm", true, "named", "named", "named"],
  ["B30", "ls /sessions/s/mnt/outputs/*.tmp | xargs -n1 rm", true, "named", "named", "named"],
  ["B31", "ls /sessions/s/mnt/outputs/*.tmp | xargs -n 1 rm", true, "named", "inferred", "named"],
  ["B32", "ls /sessions/s/mnt/outputs/*.tmp | xargs -I{} rm {}", true, "named", "inferred", "named"],
  ["B33", "ls /sessions/s/mnt/outputs/*.tmp | xargs -I {} rm {}", true, "named", "inferred", "named"],
  ["B34", "ls /sessions/s/mnt/outputs/*.tmp | xargs -I % rm %", true, "named", "inferred", "named"],
  ["B35", "ls /sessions/s/mnt/outputs/*.tmp | xargs -L 1 rm", true, "named", "inferred", "named"],
  ["B36", "ls /sessions/s/mnt/outputs/*.tmp | xargs -t rm", true, "named", "named", "named"],
  ["B37", "ls /sessions/s/mnt/outputs/*.tmp | xargs -r -n 1 rm", true, "named", "inferred", "named"],
  ["B38", "ls /sessions/s/mnt/outputs/*.tmp | xargs --max-args=1 rm", true, "named", "named", "named"],
  ["B39", "ls /sessions/s/mnt/outputs/*.tmp | xargs --null rm", true, "named", "named", "named"],
  ["B40", "ls /sessions/s/mnt/outputs/*.tmp | xargs -d '\\n' rm", true, "named", "inferred", "named"],
  ["B41", "ls /sessions/s/mnt/outputs/*.tmp | xargs -P 4 rm", true, "named", "inferred", "named"],
  ["B42", "sudo -n rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["B43", "sudo -E rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["B44", "sudo -u root rm -rf /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["B45", "timeout -k 5 10 rm -rf /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["B46", "timeout -s KILL 10 rm -rf /sessions/s/mnt/outputs/x", true, "named", "inferred", "named"],
  ["B47", "nice -n 19 rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["B48", "nice -19 rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["B49", "find /sessions/s/mnt/outputs -name '*.tmp' -exec rm -rf {} +", true, "named", "named", "named"],
  ["B50", "env -i PATH=/bin rm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  [
    "B51",
    "python3 -c \"import subprocess; subprocess.run('rm -rf /sessions/s/mnt/outputs/x', shell=True, check=True)\"",
    true,
    "named",
    "inferred",
    "named",
  ],
  ["B52", "python3 -c \"import os; os.system(f'rm -rf /sessions/s/mnt/outputs/{d}')\"", true, "named", "inferred", "named"],
  ["B53", "bash <<'EOF'\nrm -rf /sessions/s/mnt/outputs/x\nEOF", true, "named", "named", "named"],
  ["B54", "cat <<'EOF' | bash\nrm -rf /sessions/s/mnt/outputs/x\nEOF", true, "named", "named", "named"],
  ["B55", "sh -c 'rm -rf /sessions/s/mnt/outputs/x'", true, "named", "named", "named"],
  ["B56", 'bash -c "rm -rf /sessions/s/mnt/outputs/x"', true, "named", "named", "named"],
  ["B57", "bash -c 'set -e; rm -rf /sessions/s/mnt/outputs/x'", true, "named", "named", "named"],
  ["B58", "bash -ec 'rm -rf /sessions/s/mnt/outputs/x'", true, "named", "inferred", "named"],
  ["B59", "bash -c rm\\ -rf\\ /sessions/s/mnt/outputs/x", true, "named", "inferred", "inferred"],
  ["B60", "true &\nrm -rf /sessions/s/mnt/outputs/x", true, "named", "named", "named"],
  ["B61", "sleep 1 & rm -rf /sessions/s/mnt/outputs/x; wait", true, "named", "inferred", "named"],
  ["B62", 'bash -c "cd /tmp && rm -rf /sessions/s/mnt/outputs/x"', true, "named", "named", "named"],
  ["B63", "( rm -rf /sessions/s/mnt/outputs/x )", true, "named", "named", "named"],
  ["B64", "$( rm -rf /sessions/s/mnt/outputs/x )", true, "named", "named", "named"],
  ["B65", "for f in x; do rm -rf /sessions/s/mnt/outputs/$f; done", true, "named", "named", "named"],
  ["B66", "for f in x; do\n  rm -rf /sessions/s/mnt/outputs/$f\ndone", true, "named", "named", "named"],
  ["B67", 'while read f; do rm -rf "/sessions/s/mnt/outputs/$f"; done < list', true, "named", "named", "named"],
  ["B68", "if true; then\n  rm -rf /sessions/s/mnt/outputs/x\nfi", true, "named", "named", "named"],
  ["B69", "clean() { rm -rf /sessions/s/mnt/outputs/x; }; clean", true, "named", "named", "named"],
  ["B70", "clean(){\n  rm -rf /sessions/s/mnt/outputs/x\n}\nclean", true, "named", "named", "named"],
  ["B71", 'rm -f "/sessions/s/mnt/outputs/#1.md"', true, "named", "named", "named"],
  ["B72", 'rm -f "/sessions/s/mnt/outputs/issue #1.md"', true, "named", "named", "named"],
  ["B73", "rm -f /sessions/s/mnt/outputs/x\\ \\#1.md", true, "named", "named", "named"],
  ["X1", "ls /sessions/s/mnt/outputs/*.tmp | xargs -I{} echo rm {}", true, "named", "inferred", "inferred"],
  ["X2", "ls /sessions/s/mnt/outputs/*.tmp | xargs -n1 echo rm", true, "named", "inferred", "inferred"],
  ["X3", "ls /sessions/s/mnt/outputs/*.tmp | xargs -I {} echo rm -f {}", true, "named", "inferred", "inferred"],
  ["X4", "ls /sessions/s/mnt/outputs/*.tmp | xargs -0 echo rm", true, "named", "inferred", "inferred"],
];

describe("outputs-delete basis over the shape table", () => {
  it("parsed the whole table", () => {
    expect(ROWS.length).toBe(273);
  });
  it.each(ROWS)("%s: %j", (_id, cmd, flags, _statementRule, _operandRuleV1, want) => {
    expect(isOutputsDelete(cmd)).toBe(flags);
    if (want === null || want === "any") return;
    expect(outputsDeleteBasis(cmd)).toBe(want);
  });
});
