// P8b — boot the user's OWN rootfs.img as a real Apple-VZ microVM (fix plan §7a Route 2 / §8.4-P8b).
//
// ⚠ TESTED INFEASIBLE via a GENERIC VZ host (Lima) — 2026-06-21. The Cowork rootfs's PID-1 init is
// Anthropic's **`coworkd`**, not standard systemd/cloud-init. Booted under Lima's VZ it loops on
// "failed to mount smol-bin: smol-bin device not found after 10s" — i.e. the rootfs is HARDWIRED to the
// real Cowork host's virtio device model (the `smol-bin` device and the control channel), which only
// Claude Desktop's own VZ host provides. cloud-init/NoCloud is present in the rootfs but never reached
// (coworkd hijacks boot before multi-user), so Lima can never SSH in / install its guest agent → the start
// hangs. Replicating Anthropic's device model is out of scope.
//
// → THE SUPPORTED REAL-ROOTFS PARITY PATH IS P8a (`scripts/build-rootfs-image.ts`): `docker import` takes
//   the rootfs FILESYSTEM and the harness execs the agent directly — bypassing `coworkd` init entirely, so
//   it sidesteps the host-device coupling. P8a is verified working (true byte-for-byte parity, omitted:[]).
//
// This script is kept as the reproducible diagnostic for the finding. Running it will boot the VM (you'll
// see the coworkd/smol-bin loop in ~/.lima/<instance>/serialv.log) and then hang on guest-agent — Ctrl-C
// and `--delete`.
//
//   npx tsx scripts/boot-rootfs-vz.ts          # attempt the boot (demonstrates the coworkd blocker)
//   npx tsx scripts/boot-rootfs-vz.ts --delete # tear it down

import { spawnSync } from "node:child_process";
import { mkdtempSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join, dirname } from "node:path";

const BUNDLE = join(homedir(), "Library", "Application Support", "Claude", "vm_bundles", "claudevm.bundle");
const ROOTFS = join(BUNDLE, "rootfs.img");
const INSTANCE = "cowork-rootfs-vm";
const WORK = join(homedir(), ".cowork-harness", "rootfs-vm-work");

function lima(args: string[], opts: { capture?: boolean } = {}): { status: number; stdout: string } {
  const r = spawnSync("limactl", args, { encoding: "utf8", stdio: opts.capture ? "pipe" : ["ignore", "pipe", "inherit"] });
  return { status: r.status ?? 1, stdout: r.stdout ?? "" };
}

function status(): string {
  const r = lima(["list", "--format", "{{.Status}}", INSTANCE], { capture: true });
  return r.stdout.trim() || "Absent";
}

if (process.argv.includes("--delete")) {
  lima(["stop", "-f", INSTANCE]);
  lima(["delete", "-f", INSTANCE]);
  console.log(`deleted ${INSTANCE}`);
  process.exit(0);
}

if (!existsSync(ROOTFS)) throw new Error(`rootfs not found at ${ROOTFS} — open Claude Desktop once to stage it`);
mkdirSync(WORK, { recursive: true });

if (status() === "Running") {
  console.error(`${INSTANCE} already running`);
  console.log(INSTANCE);
  process.exit(0);
}

// Boot the rootfs.img directly as the VM disk. No `provision` toolchain (the rootfs is already a full
// system); a single system block just links the host-mounted agent onto PATH. The work root mounts at
// /sessions so the agent's cwd is a real /sessions/<id> dir (SPEC §9), matching L1/L2.
const config = `# Generated by cowork-harness scripts/boot-rootfs-vz.ts — P8b rootfs \`max\` tier (Apple VZ).
vmType: "vz"
arch: "aarch64"
images:
  - location: "file://${ROOTFS}"
    arch: "aarch64"
cpus: 2
memory: "2GiB"
disk: "20GiB"
mounts:
  - location: "${WORK}"
    mountPoint: "/sessions"
    writable: true
  - location: "${BUNDLE}"
    mountPoint: "/opt/cowork/agent-bundle"
    writable: false
provision:
  - mode: system
    script: |
      #!/bin/sh
      # The staged agent ELF lives in the user's claude-code-vm dir; the rootfs already has the runtime.
      # (For a real run the harness mounts the agent like L1/L2; here we just prove the rootfs boots.)
      echo "rootfs VM up: $(uname -a)"
networks: []
`;

const tmp = mkdtempSync(join(tmpdir(), "cowork-rootfs-vm-"));
const cfgPath = join(tmp, "rootfs-vm.yaml");
writeFileSync(cfgPath, config);

console.error(`creating ${INSTANCE} from ${ROOTFS} (Apple VZ; Lima copies the ~10GB image + boots via cloud-init NoCloud)…`);
if (status() === "Absent") {
  const c = lima(["create", "--name", INSTANCE, cfgPath, "--tty=false"]);
  if (c.status !== 0) throw new Error(`limactl create failed (exit ${c.status})`);
}
const s = lima(["start", INSTANCE, "--tty=false"]);
if (s.status !== 0) throw new Error(`limactl start failed (exit ${s.status}) — see Lima output above`);
console.error(`booted ${INSTANCE}.`);
console.log(INSTANCE);
